# Where is repository with prebuilt OSv packages.
repo_url: https://mikelangelo-capstan.s3.amazonaws.com/

# Don't use KVM feature.
# This feature requires exclusive access so if any other
# hypervisor (besides qemu) locks it, then 'capstan package compose'
# would result in error.
disable_kvm: true
